### ISSUE TITLE
NullPointerException when running server

### ISSUE THREAD

**Issue by cgraber** [IllinoisCogComp/open-eval#176]
I'm running the following main class:
```
public static void main(String[] argv) throws IOException {
        Annotator annotator = new NERAnnotator();

        Server server = new Server(48379, null, annotator);

        fi.iki.elonen.util.ServerRunner.executeInstance(server);
    }
```

The ip address never gets printed; instead, the following exception is thrown:

 ```
java.lang.NullPointerException
	at edu.illinois.cs.cogcomp.openeval.learner.Server.printListeningAddress(Server.java:62)
	at edu.illinois.cs.cogcomp.openeval.learner.Server.start(Server.java:56)
	at fi.iki.elonen.util.ServerRunner.executeInstance(ServerRunner.java:51)
	at annotators.NERAnnotator.main(NERAnnotator.java:46)
	... 6 more

```

**Comment by cgraber** [comment]
Another thing to add: when I run this on my local machine, I do not get this first null pointer exception; however, when I put the url in the website and try to run the experiment, I get a different null pointer exception:
```
SEVERE: Error: java.lang.NullPointerException : null
java.lang.NullPointerException
	at edu.illinois.cs.cogcomp.openeval.learner.InfoController.addServerSettings(InfoController.java:38)
	at edu.illinois.cs.cogcomp.openeval.learner.InfoController.get(InfoController.java:22)
	at fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(RouterNanoHTTPD.java:378)
	at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:479)
	at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:558)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:840)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189)
	at java.lang.Thread.run(Thread.java:745)
```
